[package]
name = "streamdeck-strip-render"
version = "0.1.0"
edition = "2024"

[features]
strict-rendering = []
super-sample = []

[dependencies]
image = { version = "0.25", default-features = false, features = ["png", "bmp", "jpeg"] }
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
serde_json = "1.0"

# Error Handling
anyhow = "1.0"

# Logging
log = "0.4"

# Font handling
ab_glyph = "0.2"

# Image Handling
base64 = "0.22"

# SVG Handling
resvg = { version = "0.47", default-features = false, features = ["text", "system-fonts"] }

[dev-dependencies]
env_logger = "0.11"