[package]
name = "streamdeck-strip-render"
version = "0.1.0"
edition = "2024"

[features]
strict-rendering = []

[dependencies]
image = { version = "0.25", default-features = false, features = ["png", "bmp", "tiff"] }
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
serde_json = "1.0"

# Error Handling
anyhow = "1.0"

# Logging
log = "0.4"

# Font handling
ab_glyph = "0.2"

# Image Handling
base64 = "0.22"
resvg = "0.47"
usvg = "0.47"
tiny-skia = "0.12"

[dev-dependencies]
env_logger = "0.11"